parameters:
#    article_user.example.class: Article\UserBundle\Example

services:
#    article_user.example:
#        class: %article_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

# src/Acme/UserBundle/Resources/config/services.yml
services:
    acme_user.registration.form.type:
        class: User\UserBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: user_user_registration }