
menu:
    resource: "@MenuBundle/Resources/config/routing.yml"
    prefix:   /

# app:
#     resource: @AppBundle/Controller/
#     type:     annotation

user_user:
    resource: "@UserUserBundle/Resources/config/routing.yml"
    prefix:   /

article_general:
    resource: "@ArticleGeneralBundle/Resources/config/routing.yml"
    prefix:   /

# # app/config/routing.yml
# fos_user:
#     resource: "@FOSUserBundle/Resources/config/routing/all.xml"

