# app/config/security.yml
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512


    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider:  form.csrf_provider
                login_path:     fos_user_security_login
                use_forward:    false
                check_path:     fos_user_security_check
                failure_path:   null
                default_target_path: /
                remember_me:    true
                # form_register:   fos_user_registration_register
            logout:       
                path:     fos_user_security_logout
                target:   /
            anonymous:    true
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN


    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/ajouter, role: ROLE_ADMIN }
