services:
#    menu.example:
#        class: MenuBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
# src/Acme/MainBundle/Resources/config/services.yml

    app.menu_builder:
        class: MenuBundle\Menu\MenuBuilder
        arguments: ["@knp_menu.factory"]

    app.main_menu:
        class: Knp\Menu\MenuItem # the service definition requires setting the class
        factory_service: app.menu_builder
        factory_method: createMainMenu
        arguments: ["@request_stack"]
        tags:
            - { name: knp_menu.menu, alias: main } # The alias is what is used to retrieve the menu



    app.sidebar_menu:
        class: Knp\Menu\MenuItem
        factory_service: app.menu_builder
        factory_method: createSidebarMenu
        arguments: ["@request_stack"]
        tags:
            - { name: knp_menu.menu, alias: sidebar } # Named "sidebar" this time
